#baseurl: /datatables-cn
baseurl:
#baseurl: /www
#port: 341
wlan_url: http://datatables.club
en_url: https://datatables.net
encoding: utf-8
exclude: ['*.bat','*.iml','*.md','LICENSE','.idea','*.custom']
#destination: ./_site
#destination: C:\code\xampp\htdocs
dtversion: 1.10.15
email: thxopen@datatables.club
github: https://github.com/gclsoft/datatables-cn/blob/gh-pages/

# page config
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"
sitename: Datatables 中文网
description: > # this means to ignore newlines until "baseurl:"
  Datatables是一款基于jQuery表格插件。目前，Datatables最新版本为1.10.15。
      Datatables中文网致力于为广大国内开发者提供详尽的中文文档、代码实例等，助力开发者使用这个jQuery表格插件